### ISSUE TITLE
how to evaluate

### ISSUE THREAD

**Issue by ccxietao** [alicranck/instance-seg#4]
I successfully trained the data set, but I don't know how to test and evaluate

**Comment by alicranck** [comment]
Hi,
After you trained the network you can use the 'evaluate_model' function in 'evaluate.py' to check the performance on a test set you provide. For the metric I used average dice score.

**Comment by ccxietao** [comment]
> Hi,
> After you trained the network you can use the 'evaluate_model' function in 'evaluate.py' to check the performance on a test set you provide. For the metric I used average dice scor

**Comment by ccxietao** [comment]
> Hi,
> After you trained the network you can use the 'evaluate_model' function in 'evaluate.py' to check the performance on a test set you provide. For the metric I used average dice score.

Hello, I need to write a program that can call the evaluate_model function myself?

**Comment by ccxietao** [comment]
> Hi,
> After you trained the network you can use the 'evaluate_model' function in 'evaluate.py' to check the performance on a test set you provide. For the metric I used average dice score.

I am training my own dataset, there are only two classes including the background, but there are hundreds of overlapping instances on each image. The effect of running out with your code is not ideal, and the overlapping instances are divided into an instance

**Comment by alicranck** [comment]
I'm not sure I understand what you mean but it may very well be the case that this network is not suited for your purposes. If you can elaborate a bit more I will try to help but do consider that this was intended as a research project and is not ready for production.
