### ISSUE TITLE
evaluate

### ISSUE THREAD

**Issue by ccxietao** [alicranck/instance-seg#5]
Hello, if I want to use the map to evaluate the performance of the model, how should I modify the code?

**Comment by alicranck** [comment]
Do you mean the COCO mAP metric? I didn't write a function to evaluate mAP on an arbitrary dataset. if you use COCO they have a python API with mAP support here - https://github.com/cocodataset/cocoapi

I might take a look at writing some function to calculate it on any dataset. Of course you are welcome to add it as well if you want.
